runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /stylesheets/(.*\.(css)) 
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(css))

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
